### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by DavidDury** [epomatti/azure-multiregion-aks-cluster#3]
Hi,

In the readme is stated:

### 5 - Helm Setup + Workload Identity

This will deploy the Workload Identity components using a Helm provider.

```sh
terraform -chdir='infrastructure/helm' init
terraform -chdir='infrastructure/helm' apply -auto-approve
```

**This step needs to be performed in the Main and Failover instances.** What do you mean by this?

**Comment by epomatti** [comment]
It means you need to apply this command to the main cluster, and then apply it again to the failover cluster. Since for this demonstration the configuration is performed from within the private network.
